### ISSUE TITLE
Not Updated

### ISSUE THREAD

**Issue by NoelJacob** [VSCodium/vscodium-insiders#2]
This repository isn't updated. It would be really cool if you could keep it maintained.

**Comment by stripedpajamas** [comment]
It should self-maintain once we get it set up, but I haven't had a chance to do so yet.

**Comment by 8thHalfHour** [comment]
This project is both amazing and essential for all of the security it adds. Thank you so much for your hard work. Is there an expected date for Insider releases becoming available?

**Comment by Metal-Mighty** [comment]
I'd be interested for this as well, especially for the preferences sync feature ! Hope it becomes a reality soon so I can switch from the MS VSCode 😁

**Comment by GitMensch** [comment]
This repo is only the place for distribution, so there's no need any more to update here - other than the releases https://github.com/VSCodium/vscodium-insiders/releases which is done automatically - so can be closed, too.

As the build scripts (not the source either, apart from the patches) is hosted in the vscodium repo the actions to build it are found there, too: https://github.com/VSCodium/vscodium/actions.
So if (as currently) vscodium-insiders doesn't build there (and therefore no releases are automatically uploaded here), it would be good to report there.

Summary: I suggest to close this issue and _maybe_ also disable the issue tracker with leaving a note about the build/release process in README. @stripedpajamas @daiyam What do you think?

**Comment by daiyam** [comment]
yep!
